name: Deploy Docker App on pavan-runner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build & Deploy on EC2 via jyo-runner
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Stop Existing Containers (if any)
        run: |
          cd /home/ubuntu/demo1
          docker compose down || true

      - name: Build and Run App with Docker Compose
        run: |
          cd /home/ubuntu/jyo
          docker compose up -d --build
